name: reader
description: Lightweight library that allows to read single strings, ints and doubles from stdin
  in a simple and straightforward way.
version: 1.0.0
repository: https://github.com/Diviloper/reader

environment:
  sdk: '>=2.7.0 <3.0.0'

dev_dependencies:
  pedantic: ^1.9.2
  test: ^1.15.3
  mockito: ^4.1.1
